import type { VercelRequest, VercelResponse } from "@vercel/node";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const body = typeof req.body === "string" ? JSON.parse(req.body) : req.body;
    const { title, priority, issueKey, assignee, category, description, webhookUrl: customWebhookUrl } = body;

    const webhookUrl = customWebhookUrl || process.env.SLACK_WEBHOOK_URL;
    if (!webhookUrl) {
      return res.status(500).json({ error: "Slack webhook URL not configured" });
    }

    const priorityEmoji =
      priority === "High" ? "🔴" : priority === "Medium" ? "🟡" : "🟢";

    const slackMessage = {
      text: `🚨 New PM Task Created: ${title}`,
      blocks: [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*🚨 New PM Task Created*`,
          },
        },
        {
          type: "section",
          fields: [
            { type: "mrkdwn", text: `*Title:*\n${title}` },
            { type: "mrkdwn", text: `*Priority:*\n${priorityEmoji} ${priority}` },
            { type: "mrkdwn", text: `*Jira Ticket:*\n${issueKey || "N/A"}` },
            { type: "mrkdwn", text: `*Assigned To:*\n${assignee || "Unassigned"}` },
            ...(category ? [{ type: "mrkdwn", text: `*Category:*\n${category}` }] : []),
          ],
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Description:*\n${description || "No description provided."}`,
          },
        },
        {
          type: "context",
          elements: [
            {
              type: "mrkdwn",
              text: "Generated by *PM Daily Copilot* · Founder's Compass",
            },
          ],
        },
      ],
    };

    const response = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(slackMessage),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Slack API error: ${response.status} ${errorText}`);
    }

    return res.status(200).json({ success: true });
  } catch (e: any) {
    console.error("Slack API Error:", e);
    return res.status(500).json({ error: "Slack API Error", details: e.message });
  }
}
