import { useState, useEffect } from "react";
import { Calendar, ListPlus, Download, MoreHorizontal } from "lucide-react";
import { downloadActionPlanICS } from "@/lib/calendar";
import type { AnalysisResult, Memory } from "@/types/copilot";
import { Switch } from "@/components/ui/switch";
import { Input } from "@/components/ui/input";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { useAuth } from "@/contexts/AuthContext";

interface RightRailProps {
  result: AnalysisResult | null;
  memory: Memory;
  useMemory: boolean;
  onToggleUseMemory: (v: boolean) => void;
  onSetGoal: (v: string) => void;
  onClear: () => void;
}

const ALL_ACTIVITY = [
  { tone: "success" as const, text: "Payment crash issue updated", time: "2h ago" },
  { tone: "info" as const, text: "New bug imported from Jira", time: "3h ago" },
  { tone: "warning" as const, text: "Action plan generated", time: "3h ago" },
  { tone: "success" as const, text: "Server issue resolved", time: "5h ago" },
  { tone: "info" as const, text: "Slack thread synced", time: "1d ago" },
  { tone: "warning" as const, text: "Goal updated", time: "2d ago" },
  { tone: "success" as const, text: "Memory context refreshed", time: "3d ago" },
];

export const RightRail = ({
  result,
  memory,
  useMemory,
  onToggleUseMemory,
  onSetGoal,
  onClear,
}: RightRailProps) => {
  const [activityExpanded, setActivityExpanded] = useState(false);
  const [integrations, setIntegrations] = useState<Record<string, boolean>>({
    Jira: true,
    "Google Calendar": true,
  });

  const total = result ? result.topPriorities.length + result.secondary.length + result.ignore.length : 0;
  const high = result?.topPriorities.filter((p) => p.impact === "High").length ?? 0;
  const low = result?.ignore.length ?? 0;

  const requireResult = (action: string): boolean => {
    if (result) return true;
    toast.error("Nothing to send", {
      description: `Run an analysis first, then ${action}.`,
    });
    return false;
  };

  const { user } = useAuth();
  const [mapping, setMapping] = useState<Record<string, string>>({});

  useEffect(() => {
    const fetchMapping = async () => {
      if (!user) return;
      try {
        const { db } = await import("@/lib/firebase");
        const { doc, getDoc } = await import("firebase/firestore");
        const docRef = doc(db, "team_mapping", user.uid);
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) setMapping(docSnap.data());
      } catch (e) {
        console.error("Error fetching mapping in RightRail:", e);
      }
    };
    fetchMapping();
  }, [user]);

  const handleCreateJira = async () => {
    if (!requireResult("create Jira tasks")) return;
    const mainTask = result!.topPriorities[0];
    if (!mainTask) {
      toast.error("No top priorities found to export.");
      return;
    }
    const toastId = toast.loading("Creating Jira ticket...");
    const categoryKey = mainTask.category.toLowerCase();
    const assigneeId = mapping[categoryKey];

    try {
      const response = await fetch("/api/jira/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          task: mainTask.task,
          priority: mainTask.impact,
          category: mainTask.category,
          assigneeId: assigneeId !== "unassigned" ? assigneeId : undefined,
          description: `${mainTask.reasoning}\n\nGenerated by Founder's Compass.`,
          dueDate: mainTask.dueDate,
        }),
      });
      const text = await response.text();
      let data;
      try {
        data = text ? JSON.parse(text) : {};
      } catch {
        throw new Error(`Invalid server response (Status ${response.status})`);
      }
      if (!response.ok) {
        throw new Error(data.details || data.error || data.message || `Error ${response.status}`);
      }
      toast.success("Jira ticket created", {
        id: toastId,
        description: `${data.issueKey} is now live.`,
        action: { label: "Open", onClick: () => window.open(data.issueUrl, "_blank") },
      });
    } catch (error: any) {
      toast.error("Jira export failed", { id: toastId, description: error.message });
    }
  };

  const handleAddCalendar = () => {
    if (!requireResult("add to calendar")) return;
    try {
      downloadActionPlanICS(result!.actionPlan);
      toast.success("Calendar (.ics) downloaded");
    } catch (error) {
      console.error("Calendar export failed:", error);
      toast.error("Failed to generate calendar file");
    }
  };

  const handleExport = () => {
    if (!requireResult("export a report")) return;
    const lines: string[] = [
      `# Founder's Compass — ${new Date().toLocaleDateString()}`,
      "",
      `## Top priorities (${result!.topPriorities.length})`,
      ...result!.topPriorities.map((p, i) => `${i + 1}. [${p.impact}] ${p.task}\n   - ${p.reasoning}`),
      "",
      `## Secondary (${result!.secondary.length})`,
      ...result!.secondary.map((s, i) => `${i + 1}. ${s}`),
      "",
      `## Ignored (${result!.ignore.length})`,
      ...result!.ignore.map((s, i) => `${i + 1}. ${s}`),
      "",
      `## Action plan`,
      ...result!.actionPlan.map((a, i) => `${i + 1}. ${a.task} — ${a.nextStep} (~${a.timeEstimate})`),
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `founders-compass-${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Report downloaded");
  };

  const toggleIntegration = (name: string) => {
    setIntegrations((prev) => {
      const next = { ...prev, [name]: !prev[name] };
      toast.message(`${name} ${next[name] ? "connected" : "disconnected"}`);
      return next;
    });
  };

  const visibleActivity = activityExpanded ? ALL_ACTIVITY : ALL_ACTIVITY.slice(0, 4);

  return (
    <aside className="space-y-3">
      {/* Today's summary */}
      <Panel title="Summary" right={<Calendar className="h-3.5 w-3.5 text-muted-foreground" />}>
        <div className="grid grid-cols-2 gap-1.5">
          <Stat label="Total" value={total} />
          <Stat label="Highest" value={high} tone="high" />
          <Stat label="Medium" value={result?.secondary.length ?? 0} tone="medium" />
          <Stat label="Low" value={low} tone="low" />
        </div>
      </Panel>

      {/* Quick actions */}
      <Panel
        title="Quick actions"
        right={
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button className="h-6 w-6 rounded hover:bg-muted flex items-center justify-center transition-colors">
                <MoreHorizontal className="h-3.5 w-3.5 text-muted-foreground" />
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onSelect={handleAddCalendar}>
                <Calendar className="h-3.5 w-3.5 mr-2" />
                Add to calendar
              </DropdownMenuItem>
              <DropdownMenuItem onSelect={handleExport}>
                <Download className="h-3.5 w-3.5 mr-2" />
                Export report
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        }
      >
        <button
          onClick={handleCreateJira}
          className="w-full flex items-center gap-2 px-2 py-2 rounded hover:bg-muted text-[12.5px] text-foreground transition-colors"
        >
          <ListPlus className="h-3.5 w-3.5 text-primary" />
          Create Jira task
        </button>
      </Panel>

      {/* Memory */}
      <Panel
        title="Memory context"
        right={<Switch checked={useMemory} onCheckedChange={onToggleUseMemory} />}
      >
        <div className="space-y-3">
          <div>
            <label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
              Goal
            </label>
            <Input
              value={memory.userProfile.goal}
              onChange={(e) => onSetGoal(e.target.value)}
              placeholder="e.g. Reach $10k MRR by Q3"
              className="h-8 mt-1 text-[12px]"
            />
          </div>
          {memory.patterns.length > 0 && (
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1.5">
                Patterns
              </p>
              <div className="flex flex-wrap gap-1">
                {memory.patterns.map((p) => (
                  <span key={p} className="text-[10.5px] px-1.5 py-0.5 rounded-sm bg-muted text-muted-foreground font-mono">
                    {p}
                  </span>
                ))}
              </div>
            </div>
          )}
          {memory.pastPriorities.length > 0 && (
            <button
              onClick={onClear}
              className="text-[11px] text-muted-foreground hover:text-destructive transition-colors"
            >
              Reset memory
            </button>
          )}
        </div>
      </Panel>

      {/* Integrations */}
      <Panel id="integrations-panel" title="Integrations">
        <div className="space-y-1.5">
          {Object.entries(integrations).map(([name, connected]) => (
            <div key={name} className="flex items-center justify-between text-[12px]">
              <span className="font-medium text-foreground/85">{name}</span>
              <button
                onClick={() => toggleIntegration(name)}
                className={cn(
                  "text-[10px] font-semibold px-1.5 py-0.5 rounded-sm transition-colors",
                  connected
                    ? "bg-priority-low/10 text-priority-low hover:bg-priority-low/20"
                    : "bg-muted text-muted-foreground hover:bg-muted/70"
                )}
              >
                {connected ? "Connected" : "Off"}
              </button>
            </div>
          ))}
        </div>
      </Panel>

      {/* Recent activity */}
      <Panel title="Recent activity">
        <ul className="space-y-2">
          {visibleActivity.map((a, i) => (
            <Activity key={i} tone={a.tone} text={a.text} time={a.time} />
          ))}
        </ul>
        <button
          onClick={() => setActivityExpanded((v) => !v)}
          className="mt-2.5 text-[11px] font-medium text-primary hover:underline"
        >
          {activityExpanded ? "Show less" : "Show all"}
        </button>
      </Panel>
    </aside>
  );
};

const Panel = ({
  id,
  title,
  right,
  children,
}: {
  id?: string;
  title: string;
  right?: React.ReactNode;
  children: React.ReactNode;
}) => (
  <div id={id} className="rounded-md border border-border bg-card">
    <header className="flex items-center justify-between px-3 py-2 border-b border-border">
      <h3 className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
        {title}
      </h3>
      {right}
    </header>
    <div className="p-3">{children}</div>
  </div>
);

const Stat = ({ label, value, tone }: { label: string; value: number; tone?: "high" | "medium" | "low" }) => {
  const accent =
    tone === "high"
      ? "text-priority-high"
      : tone === "medium"
      ? "text-priority-medium"
      : tone === "low"
      ? "text-priority-low"
      : "text-foreground";
  return (
    <div className="rounded border border-border p-2 flex items-center justify-between">
      <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
        {label}
      </p>
      <p className={cn("text-[14px] font-semibold tabular-nums", accent)}>{value}</p>
    </div>
  );
};

const Activity = ({ tone, text, time }: { tone: "success" | "info" | "warning"; text: string; time: string }) => {
  const dot = {
    success: "bg-priority-low",
    info: "bg-info",
    warning: "bg-priority-medium",
  }[tone];
  return (
    <li className="flex items-center gap-2 text-[12px]">
      <span className={`h-1.5 w-1.5 rounded-full ${dot} shrink-0`} />
      <span className="flex-1 text-foreground/85 truncate">{text}</span>
      <span className="text-muted-foreground text-[10.5px] shrink-0">{time}</span>
    </li>
  );
};
